// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "1 day": {                                       "en": "1 day",                                           "de": "1 Tag",                                           "ru": "1 день",                                          "pt": "1 dia",                                           "nl": "1 dag",                                           "fr": "Un jour",                                         "it": "1 giorno",                                        "es": "1 día",                                           "pl": "1 dzień"},
    "1 months": {                                    "en": "1 months",                                        "de": "1 Monat",                                         "ru": "1 месяц",                                         "pt": "1 mês",                                           "nl": "1 maanden",                                       "fr": "1 mois",                                          "it": "1 mese",                                          "es": "1 mes",                                           "pl": "1 miesiąc"},
    "1 week": {                                      "en": "1 week",                                          "de": "1 Woche",                                         "ru": "1 неделя",                                        "pt": "1 semana",                                        "nl": "1 week",                                          "fr": "1 semaine",                                       "it": "1 settimana",                                     "es": "1 semana",                                        "pl": "1 tydzień"},
    "1 year": {                                      "en": "1 year",                                          "de": "1 Jahr",                                          "ru": "1 год",                                           "pt": "1 ano",                                           "nl": "1 jaar",                                          "fr": "1 an",                                            "it": "1 anno",                                          "es": "1 año",                                           "pl": "1 rok"},
    "2 weeks": {                                     "en": "2 weeks",                                         "de": "2 Wochen",                                        "ru": "2 недели",                                        "pt": "2 semanas",                                       "nl": "2 weken",                                         "fr": "2 semaines",                                      "it": "2 settimane",                                     "es": "2 semanas",                                       "pl": "2 tygodnie"},
    "2 years": {                                     "en": "2 years",                                         "de": "2 Jahre",                                         "ru": "2 года",                                          "pt": "2 anos",                                          "nl": "2 jaar",                                          "fr": "2 ans",                                           "it": "2 anni",                                          "es": "2 años",                                          "pl": "2 lata"},
    "3 days": {                                      "en": "3 days",                                          "de": "3 Tage",                                          "ru": "3 дня",                                           "pt": "3 dias",                                          "nl": "3 dagen",                                         "fr": "3 jours",                                         "it": "3 giorni",                                        "es": "3 días",                                          "pl": "3 dni"},
    "3 months": {                                    "en": "3 months",                                        "de": "3 Monate",                                        "ru": "3 месяца",                                        "pt": "3 meses",                                         "nl": "3 maanden",                                       "fr": "3 mois",                                          "it": "3 mesi",                                          "es": "3 meses",                                         "pl": "3 miesiące"},
    "5 days": {                                      "en": "5 days",                                          "de": "5 Tage",                                          "ru": "5 дней",                                          "pt": "5 dias",                                          "nl": "5 dagen",                                         "fr": "5 jours",                                         "it": "5 giorni",                                        "es": "5 dias",                                          "pl": "5 dni"},
    "6 months": {                                    "en": "6 months",                                        "de": "6 Monate",                                        "ru": "6 месяцев",                                       "pt": "6 meses",                                         "nl": "6 maanden",                                       "fr": "6 mois",                                          "it": "6 mesi",                                          "es": "6 meses",                                         "pl": "6 miesięcy"},
    "De-bounce interval(ms)": {                      "en": "De-bounce interval(ms)",                          "de": "Entprellzeit(ms)",                                "ru": "Минимальный интервал(ms)",                        "pt": "Intervalo de desvio (ms)",                        "nl": "De-bounce interval (ms)",                         "fr": "Intervalle de rebond (ms)",                       "it": "Intervallo di rimbalzo (ms)",                     "es": "Intervalo de rebote (ms)",                        "pl": "Interwał odbicia (ms)"},
    "Storage retention": {                           "en": "Storage retention",                               "de": "Storage Vorhaltezeit",                            "ru": "Сохранять в файле",                               "pt": "Retenção de armazenamento",                       "nl": "Opslag retentie",                                 "fr": "Conservation du stockage",                        "it": "Conservazione di memoria",                        "es": "Retención de almacenamiento",                     "pl": "Przechowywanie danych"},
    "enabled": {                                     "en": "enabled",                                         "de": "Aktiviert",                                       "ru": "активно",                                         "pt": "ativado",                                         "nl": "ingeschakeld",                                    "fr": "activée",                                         "it": "abilitato",                                       "es": "habilitado",                                      "pl": "włączony"},
    "keep forever": {                                "en": "keep forever",                                    "de": "keine automatische Löschung",                     "ru": "хранить вечно",                                   "pt": "mantenha para sempre",                            "nl": "blijf voor altijd",                               "fr": "garde pour toujours",                             "it": "tienilo per sempre",                              "es": "mantener para siempre",                           "pl": "zachowaj na zawsze"},
    "log changes interval(s) (0 = disable)": {
        "en": "still record the same values (seconds)<br>(0 = disable)",
        "de": "trotzdem gleiche Werte aufzeichnen (Sekunden) <br> (0 = deaktivieren)",
        "ru": "по-прежнему записывать те же значения (в секундах) <br> (0 = отключить)",
        "pt": "ainda gravar os mesmos valores (segundos) <br> (0 = desabilitar)",
        "nl": "nog steeds dezelfde waarden (seconden) <br> (0 = uitschakelen)",
        "fr": "toujours enregistrer les mêmes valeurs (secondes) <br> (0 = désactiver)",
        "it": "registra ancora gli stessi valori (secondi) <br> (0 = disabilita)",
        "es": "sigue registrando los mismos valores (segundos) <br> (0 = deshabilitar)",
        "pl": "nadal nagrywaj te same wartości (sekundy) <br> (0 = wyłącz)",
        "zh-cn": "仍记录相同的值（秒）<br>（0 =禁用）"
    },
    "log changes minimal delta (0 = disable delta check)": {
        "en": "Minimum difference from last value<br>(0 = disable delta check)",
        "de": "Minimale Differenz zum letzten Wert <br> (0 = Deltaprüfung deaktivieren)",
        "ru": "Минимальное отличие от последнего значения <br> (0 = отключить дельта-проверку)",
        "pt": "Diferença mínima do último valor <br> (0 = desabilitar verificação delta)",
        "nl": "Minimaal verschil met laatste waarde <br> (0 = deltablokkering uitschakelen)",
        "fr": "Différence minimale par rapport à la dernière valeur <br> (0 = désactiver la vérification delta)",
        "it": "Differenza minima dall'ultimo valore <br> (0 = disabilita il controllo delta)",
        "es": "Diferencia mínima desde el último valor <br> (0 = deshabilitar la comprobación delta)",
        "pl": "Minimalna różnica od ostatniej wartości <br> (0 = wyłącz kontrolę delta)",
        "zh-cn": "与上一个值的最小差异<br>（0 =禁用增量检查）"
    },
    "log changes only": {
        "en": "Record changes only",
        "de": "Nur Änderungen aufzeichnen",
        "ru": "Запись только изменений",
        "pt": "Registrar apenas alterações",
        "nl": "Wijzigingen alleen registreren",
        "fr": "Enregistrer les modifications uniquement",
        "it": "Registra solo le modifiche",
        "es": "Registrar solo cambios",
        "pl": "Zapisz tylko zmiany",
        "zh-cn": "仅记录更改"
    },
    "maximum datapoint count in RAM": {              "en": "maximum datapoint count in RAM",                  "de": "maximale Anzahl Datenpunkte in RAM",              "ru": "макс. кол-во значений в RAM памяти",              "pt": "contagem máxima do datapoint na RAM",             "nl": "maximum aantal datapunten in RAM",                "fr": "nombre de points de données maximum en RAM",      "it": "massimo conteggio dei punti di accesso nella RAM", "es": "recuento máximo de datos en RAM",                 "pl": "maksymalna liczba punktów w pamięci RAM"}
};